### ISSUE TITLE
Investigate Homepage center block sizing

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/website#29]
In #27 / #28 we updated some content in the center (blue) block on the homepage. The original update called for two paragraphs, but when making the change in `index.html`, that center block couldn't contain all the content:

![https://user-images.githubusercontent.com/1783439/148138405-116b63cd-3e74-42c8-810d-51fd58d247f2.png](https://user-images.githubusercontent.com/1783439/148138405-116b63cd-3e74-42c8-810d-51fd58d247f2.png)

Need to figure out why the SVG wouldn't scale appropriately, and ultimately we would like to separate the content back into two paragraphs.

/cc @esquared415

**Comment by thekaveman** [comment]
@allejo if you have some time, can you please look into this one? (Or if you know what's going on?)

**Comment by allejo** [comment]
![image](https://user-images.githubusercontent.com/1246453/148312930-fba05cbb-27c6-47e8-9917-15a49ef3793e.png)

Sorry! Haven't been following the threads here lately 😅  is the extra-wide blue background a workaround until the height is fixed?

**Comment by thekaveman** [comment]
Uh, I didn't adjust the background at all 😬 just the content inside. On my (14") laptop on Chrome it looks like:

![image](https://user-images.githubusercontent.com/1783439/148315131-71b06ed8-b17b-4fb6-92c3-81cce452f988.png)

And see the above screenshot for what it looked like with two paragraphs - that is what we actually want (separate paragraphs).

**Comment by allejo** [comment]
I optimized the SVG backgrounds a bit and used `preserveAspectRatio="none"` so that we can use it as a scalable background image that will respect the height of the content.

SVGs are extremely powerful but also... very temperamental (see the [MDN docs on the SVG sizing behavior](https://developer.mozilla.org/en-US/docs/Web/CSS/Scaling_of_SVG_backgrounds)). This, however, is a simple patch job and the design of this part of the website should be revisited if we need a more robust solution.
